<a href="https://colab.research.google.com/github/WaltsonZh/TensorFlowCourse/blob/main/L2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

> If you're running on a GPU, you'll get a message `Successfully opened dynamic library cudart64_101.dll`, if you find that anoying the following code will save you.

In [2]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf

# prevent tensorflow allocate all the memory from the GPU
physical_divices = tf.config.list_physical_devices('GPU')
# physical_divices[0] if you have only one GPU
tf.config.experimental.set_memory_growth(physical_divices[0], True)

# **Initialization**

In [ ]:
x = tf.constant(4) # dtype=int32
# print(x)

y = tf.constant(4.0) # dtype=float32
# print(y)

z = tf.constant(4, shape=(1, 1), dtype=tf.float32)
# print(z)

arr = tf.constant([[1, 2, 3], [4, 5, 6]])
# print(arr)

one = tf.ones((3, 3))
# print(one)

zero = tf.zeros((2, 3))
# print(zero)

# Identity matrix
eye = tf.eye(3)
# print(eye)

# Standard distribution
std = tf.random.normal((3, 3), mean=0, stddev=1)
# print(std)

# Uniform distribution
uni = tf.random.uniform((1, 3), minval=0, maxval=1)
# print(uni)

r = tf.range(start=1, limit=10, delta=2)
# print(r)

cast = tf.cast(r, dtype=tf.float64)
# print(cast)



# **Mathematical Operations**

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

# add = tf.add(x, y)
add = x + y
# print(add)

# sub = tf.subtract(x, y)
sub = x - y
# print(sub)

# div = tf.divide(x, y)
div = x / y
# print(div)

# mul = tf.multiply(x, y)
mul = x * y
# print(mul)

# dot = tf.reduce_sum(x * y, axis=0)
dot = tf.tensordot(x, y, axes=1)
# print(dot)

exp = x ** 5
# print(exp)

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

# matmul = tf.matmul(x, y)
matmul = x @ y
# print(matmul)

# **Indexing**

In [ ]:
x = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

# print(x[:])
# print(x[1:])
# print(x[1:3])
# print(x[::2])
# print(x[::-1])

indeces = tf.constant([0, 3])
x_ind = tf.gather(x, indeces)
# print(x_ind)

x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# print(x[0])
# print(x[0:2])
# print(x[1, 1])

# **Reshaping**

In [53]:
x = tf.range(9)

reshape = tf.reshape(x, (3, 3))
# print(reshape)

transp = tf.transpose(reshape, perm=[1, 0])
print(transp)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
